# Generated by Django 4.2.7 on 2023-11-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCommentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_comment', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('mainImage', models.ImageField(max_length=200, upload_to='upload/%Y/%m/%d/')),
                ('description', models.CharField(blank=True, max_length=10000)),
                ('date_pub', models.DateTimeField(auto_now=True)),
                ('addititionalImages', models.ImageField(max_length=200, upload_to='upload/%Y/%m/%d/')),
            ],
            options={
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='NewsTopicsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Тематики новостей',
            },
        ),
        migrations.CreateModel(
            name='RegionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Регионы',
            },
        ),
    ]
