# Generated by Django 4.1.10 on 2023-12-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_message', models.DateTimeField(auto_now=True)),
                ('sender', models.TextField(max_length=100)),
                ('contact', models.TextField(max_length=100)),
                ('message', models.TextField(max_length=10000)),
            ],
            options={
                'verbose_name_plural': 'Сообщения для администрации',
                'permissions': [('view_messages', 'Can view messages')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=200, upload_to='news/%Y%m%d/')),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Медиа-материалы',
                'permissions': [('image_editor', 'Can add or delete images for publication')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PublicationsCommentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_comment', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, max_length=10000)),
                ('show_comment', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Комментарии',
                'permissions': [('moderation', 'Can set the status of the comments'), ('add_comments', 'Can add comments')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PublicationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('text', models.TextField(blank=True)),
                ('date_pub', models.DateTimeField()),
                ('show_news', models.BooleanField(default=True)),
                ('date_edit', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Публикации',
                'permissions': [('main_news_editor', 'Can edit the publications of any author'), ('news_editor', 'Can add, edit and delete only his own publications')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Тэги публикаций',
                'permissions': [('tags_editor', 'Can edit the tags')],
                'default_permissions': (),
            },
        ),
    ]
