# Generated by Django 4.1.10 on 2023-12-12 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationsmodel',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicationsmodel',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicationsmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='Тэги', to='main.tagsmodel'),
        ),
        migrations.AddField(
            model_name='publicationscommentsmodel',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.publicationsmodel'),
        ),
        migrations.AddField(
            model_name='publicationscommentsmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagesmodel',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.publicationsmodel'),
        ),
    ]
