# Generated by Django 4.2.7 on 2023-11-14 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.regionmodel'),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='topicnews',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.newstopicsmodel'),
        ),
        migrations.AddField(
            model_name='newscommentsmodel',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.newsmodel'),
        ),
        migrations.AddField(
            model_name='newscommentsmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
