# Generated by Django 4.2.7 on 2023-11-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='addititionalImages',
            field=models.ImageField(max_length=1000, upload_to='%Y%m%d-%H%M/addititional/'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='mainImage',
            field=models.ImageField(max_length=200, upload_to='%Y%m%d-%H%M/mainImage/'),
        ),
    ]
