# Generated by Django 4.1.10 on 2023-12-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_publicationsmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationsmodel',
            name='date_pub',
            field=models.DateTimeField(null=True),
        ),
    ]
