# Generated by Django 4.2.7 on 2023-11-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_newsmodel_addititionalimages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='addititionalImages',
            field=models.ImageField(max_length=1000, upload_to='main/news/%Y%m%d-%H%M/'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='mainImage',
            field=models.ImageField(max_length=200, upload_to='main/news/%Y%m%d-%H%M/'),
        ),
    ]
