# Generated by Django 4.1.10 on 2023-12-15 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_alter_publicationsmodel_date_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationsmodel',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autor', to=settings.AUTH_USER_MODEL),
        ),
    ]
