# Generated by Django 4.2.7 on 2023-11-16 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_newsmodel_addititionalimages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='addititionalImages',
        ),
    ]
