# Generated by Django 4.2.7 on 2023-11-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_newsmodel_addititionalimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscommentsmodel',
            name='show_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='show_news',
            field=models.BooleanField(default=True),
        ),
    ]
