# Generated by Django 4.2.7 on 2023-11-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_newscommentsmodel_show_comment_newsmodel_show_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscommentsmodel',
            name='text',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
