# Generated by Django 4.2.7 on 2023-11-18 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_newscommentsmodel_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newstopicsmodel',
            name='code',
        ),
        migrations.RemoveField(
            model_name='regionmodel',
            name='code',
        ),
    ]
