# Generated by Django 4.2.7 on 2023-11-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_newstopicsmodel_code_remove_regionmodel_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='topicnews',
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='topicnews',
            field=models.ManyToManyField(to='main.newstopicsmodel'),
        ),
    ]
