# Generated by Django 4.2.7 on 2023-11-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_newsmodel_topicnews_newsmodel_topicnews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='region',
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='region',
            field=models.ManyToManyField(to='main.regionmodel'),
        ),
    ]
