# Generated by Django 4.2.7 on 2023-11-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_newsmodel_region_alter_newsmodel_topicnews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsTopicsModel',
            new_name='TagsModel',
        ),
        migrations.AlterModelOptions(
            name='tagsmodel',
            options={'verbose_name_plural': 'Тэги новостей'},
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='region',
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='topicnews',
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='Тэги', to='main.tagsmodel'),
        ),
        migrations.DeleteModel(
            name='RegionModel',
        ),
    ]
