# Generated by Django 4.2.7 on 2023-11-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_newstopicsmodel_tagsmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagsmodel',
            name='categories',
            field=models.CharField(choices=[('1', 'One'), ('2', 'Two')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
