# Generated by Django 4.2.7 on 2023-11-30 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_tagsmodel_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagsmodel',
            name='categories',
        ),
    ]
