# Generated by Django 4.2.7 on 2023-12-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_tagsmodel_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_message', models.DateTimeField(auto_now=True)),
                ('sender', models.TextField(max_length=100)),
                ('contact', models.TextField(max_length=100)),
                ('message', models.TextField(max_length=10000)),
            ],
        ),
    ]
