# Generated by Django 4.2.7 on 2023-12-07 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_contactmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name_plural': 'Сообщения для администрации'},
        ),
        migrations.CreateModel(
            name='ImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/%Y%m%d-%H%M/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.newsmodel')),
            ],
            options={
                'verbose_name_plural': 'Медиа-материалы',
            },
        ),
    ]
