# Generated by Django 4.2.7 on 2023-12-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_contactmodel_options_imagesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesmodel',
            name='image',
            field=models.ImageField(upload_to='news/%Y%m%d/'),
        ),
    ]
